version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/.cert/homeoffice:/etc/ssl/certs
      #- ./backend/.cert/office:/etc/ssl/certs



  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/.cert/homeoffice:/etc/ssl/certs
      #- ./frontend/.cert/office:/etc/ssl/certs
