version: '3.8'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ${CERT_PATH}:/etc/ssl/certs

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "3000:80"   #Nginx hört auf Port 80
    volumes:
      - ${CERT_PATH}:/etc/ssl/certs
